### ISSUE TITLE
Error in GetJobs()

### ISSUE THREAD

**Issue by TylerOrtiz** [akshaysura/Sitecron#11]
When I updated to the latest version (3.0.7) I'm getting tons of errors loading my jobs.

Stack trace:
```
ManagedPoolThread #11 13:29:06 INFO  Initialize Sitecron: 3.0.7.0
ManagedPoolThread #11 13:29:06 INFO  Loading Sitecron Jobs
ManagedPoolThread #11 13:29:06 ERROR Sitecron ERROR: Object reference not set to an instance of an object.
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: SiteCron
   at Sitecron.Core.Jobs.DatabaseJobProvider.CreateSitecronJob(Item jobItem)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Sitecron.Core.Jobs.DBAndConfigJobProvider.GetJobs()
   at Sitecron.Core.DefaultScheduleManager.ScheduleAllJobs()

```

It shows no useful information as to which job is failing to load.

**Comment by akshaysura** [comment]
thank you, can you please update to the new version 3.0.9 please. Let me know if you see any issues. Also if you do not have a ton of jobs, you can switch to the db provider.

**Comment by akshaysura** [comment]
Tyler, sorry for the late reply. So you are accessing the server lets call it CM from your desktop, the CM is in a different timezone that your local machine?

**Comment by TylerOrtiz** [comment]
In the local scenario where it seems to be failing -- both server and client are in the same timezone.

**Comment by akshaysura** [comment]
Did you try switching to just the Database provider?

**Comment by TylerOrtiz** [comment]
Yes, the database provider only seems to work better at this time.
