### ISSUE TITLE
One or more exceptions occurred while processing the subscribers to the 'item:deleted:remote' event.

### ISSUE THREAD

**Issue by stewpocalypse** [akshaysura/Sitecron#24]
Found this error through our Sitecore 9.3 logs. 

`One or more exceptions occurred while processing the subscribers to the 'item:deleted:remote' event.
Exception[1]: System.InvalidOperationException 
Message[1]: Invalid event arg type: Sitecore.Data.Events.ItemDeletedRemoteEventArgs. Expected: SitecoreEventArgs 
Source[1]: Sitecore.Kernel 
   at Sitecore.Events.Event.ExtractParameters(EventArgs args)
   at Sitecore.Events.Event.ExtractParameter(EventArgs args, Int32 index)
   at Sitecron.Core.Events.SitecronDeletedHandler.OnItemDeleted(Object sender, EventArgs args)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)`

**Comment by JanBuehler** [comment]
Are you in an environment with multiple CM? In case you're not I suggest to try removing the item:deleted:remote handler as the item:deleted event should do the job.
Which version of Sitecron are you running?

**Comment by azoli** [comment]
I am experiencing the same issue. The errors appear after I scaled my CM environment to 2 instances.

@JanBuehler is it possible to release this branch as pre-release for Sitecore 9.3 to use it via NuGet package manager?
